spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_controller?serverTimezone=UTC
    username: root
    password: root
shiro:
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: true
  unauthorizedUrl: "/unauthorizedurl"
  web:
    enabled: true
  successUrl: "/success"
  loginUrl: "/doLogin"
